version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - sns_app

  mysql:
    image: mysql:5.7
    container_name: mysql

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: sns
      MYSQL_USER: django
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    expose:
      - "3306"

  sns_app:
    container_name: sns_app
    build:
      context: .
      dockerfile: ./apps/Dockerfile
    command: >
      bash -c "chmod +x ./wait-for-it.sh
      && python manage.py makemigrations
      && python manage.py migrate
      && gunicorn sns.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"
    depends_on:
      - mysql
    links:
      - mysql:mysql
    volumes:
      - ./apps:/app
    env_file:
      - ../ably_test/apps/.env
    restart: always
    entrypoint: ./wait-for-it.sh db_host:3306 --